import { Router } from "express";
import { requireAuth } from "../middleware/auth.js";

export const deployRouter = Router();

// POST /api/v1/deploy/generate — removed; deployment config is generated by the CLI
deployRouter.post("/generate", requireAuth, (_req, res) => {
  res.status(501).json({
    error: "Web-based deploy generation removed. Use the CLI: npx unideploy audit",
    code: "USE_CLI",
  });
});
