"""
FixAgent — generates patches from a remediation plan and raises a GitHub PR via Composio.
User-triggered only (never auto-applies).
"""

import json
import os
import asyncio
from google import genai
from google.genai.types import GenerateContentConfig

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "")
GOOGLE_CLOUD_PROJECT = os.getenv("GOOGLE_CLOUD_PROJECT", "")
USE_VERTEX = os.getenv("GOOGLE_GENAI_USE_VERTEXAI", "false").lower() == "true"
COMPOSIO_API_KEY = os.getenv("COMPOSIO_API_KEY", "")

PATCH_PROMPT = """You are UniDeploy's FixAgent. Generate a minimal, targeted patch to fix a security finding.

Finding:
{finding_json}

Remediation plan:
{plan_json}

Current file content ({file_path}):
```
{file_content}
```

Output: ONLY a JSON object with:
{{
  "file_path": "{file_path}",
  "new_content": "<complete new file content with the fix applied>",
  "change_summary": "one sentence describing what was changed"
}}

Rules:
- Make the SMALLEST possible change that fixes the finding
- Never remove functionality unrelated to the finding
- Preserve all existing comments and formatting style
- If you cannot safely patch this file, set new_content to null and explain in change_summary
"""


def _generate_patch_sync(finding: dict, plan: dict, file_content: str) -> dict | None:
    if USE_VERTEX:
        client = genai.Client(vertexai=True, project=GOOGLE_CLOUD_PROJECT, location="us-central1")
    else:
        client = genai.Client(api_key=GEMINI_API_KEY)

    prompt = PATCH_PROMPT.format(
        finding_json=json.dumps(finding, indent=2),
        plan_json=json.dumps(plan, indent=2),
        file_path=finding.get("file", "unknown"),
        file_content=file_content[:8000],
    )
    response = client.models.generate_content(
        model="gemini-2.5-pro",
        contents=prompt,
        config=GenerateContentConfig(
            response_mime_type="application/json",
            temperature=0.0,
        ),
    )
    text = response.text.strip()
    if "```" in text:
        text = text.split("```")[1]
        if text.startswith("json"):
            text = text[4:]
    result = json.loads(text.strip())
    if not result.get("new_content"):
        return None
    return result


def _raise_github_pr_sync(
    github_url: str,
    fix_branch: str,
    base_branch: str,
    title: str,
    body: str,
    composio_entity_id: str = "default",
) -> dict:
    """Use Composio to create a GitHub PR."""
    try:
        from composio_openai import ComposioToolSet, Action
        toolset = ComposioToolSet(api_key=COMPOSIO_API_KEY, entity_id=composio_entity_id)

        # Extract owner/repo from github_url
        parts = github_url.rstrip("/").replace(".git", "").split("/")
        owner = parts[-2]
        repo = parts[-1]

        result = toolset.execute_action(
            action=Action.GITHUB_CREATE_A_PULL_REQUEST,
            params={
                "owner": owner,
                "repo": repo,
                "title": title,
                "body": body,
                "head": fix_branch,
                "base": base_branch,
            },
        )
        pr_data = result.get("data", {})
        return {
            "pr_url": pr_data.get("html_url", ""),
            "pr_number": pr_data.get("number"),
        }
    except Exception as e:
        return {"error": str(e), "pr_url": None}


async def generate_patches(
    findings: list[dict],
    plans: list[dict],
    file_contents: dict[str, str],
) -> list[dict]:
    """
    Generate patches for each finding+plan pair.
    file_contents: {relative_path: content}
    Returns list of patch dicts with file_path and new_content.
    """
    plan_by_id = {p["finding_id"]: p for p in plans}
    patches = []
    for finding in findings:
        plan = plan_by_id.get(finding["id"])
        if not plan:
            continue
        file_path = finding.get("file", "")
        content = file_contents.get(file_path, "")
        if not content:
            continue
        try:
            patch = await asyncio.to_thread(
                _generate_patch_sync, finding, plan, content
            )
            if patch:
                patches.append(patch)
        except Exception:
            continue
    return patches


async def raise_github_pr(
    github_url: str,
    fix_branch: str,
    base_branch: str,
    findings_count: int,
    scan_id: str,
    composio_entity_id: str = "default",
) -> dict:
    """Async wrapper for raising a GitHub PR via Composio."""
    title = f"fix: [UniDeploy] Remediate {findings_count} security finding(s)"
    body = (
        f"## UniDeploy Security Fix\n\n"
        f"This PR was generated by [UniDeploy](https://unideploy.in) to remediate "
        f"**{findings_count}** security finding(s) identified in scan `{scan_id}`.\n\n"
        f"### What was changed\n"
        f"Each commit targets a specific finding with the smallest possible safe change.\n\n"
        f"### Review before merging\n"
        f"- [ ] Review each file diff carefully\n"
        f"- [ ] Run your test suite\n"
        f"- [ ] Verify the fix works in your environment\n\n"
        f"---\n*Generated by UniDeploy — production-readiness scanner for vibe-coded apps.*"
    )
    return await asyncio.to_thread(
        _raise_github_pr_sync, github_url, fix_branch, base_branch, title, body, composio_entity_id
    )
